esp_toml_version = 1.0

multipart = true
chip = "esp32-s3"
supported_apps = [ "Echo-Ear-AI-Voice-Agent" ]

[Echo-Ear-AI-Voice-Agent]
image.esp32-s3.parts = [
  "https://esp-agents-firmware-prebuilt.s3.ap-northeast-1.amazonaws.com/echo_ear/bootloader.bin",
  "https://esp-agents-firmware-prebuilt.s3.ap-northeast-1.amazonaws.com/echo_ear/partition-table.bin",
  "https://esp-agents-firmware-prebuilt.s3.ap-northeast-1.amazonaws.com/echo_ear/ota_data_initial.bin",
  "https://esp-agents-firmware-prebuilt.s3.ap-northeast-1.amazonaws.com/echo_ear/esp_agent_voice_chat.bin",
  "https://esp-agents-firmware-prebuilt.s3.ap-northeast-1.amazonaws.com/echo_ear/srmodels.bin"
]
image.esp32-s3.addresses = [ "0x0", "0x8000", "0x1c000", "0x30000", "0xe2c000" ]
readme.text = "<README_FILE_URL>"