esp_toml_version = 1.0

multipart = true
chip = "esp32-s3"
supported_apps = [ "M5Stack-CoreS3-AI-Voice-Agent" ]

[M5Stack-CoreS3-AI-Voice-Agent]
icon = "https://github.com/espressif/esp-agents-firmware/wiki/images/M5StackCoreS3Listening.png"
image.esp32-s3.parts = [
  "https://esp-agents-firmware-prebuilt.s3.ap-northeast-1.amazonaws.com/friend/m5stack_cores3/bootloader.bin",
  "https://esp-agents-firmware-prebuilt.s3.ap-northeast-1.amazonaws.com/friend/m5stack_cores3/partition-table.bin",
  "https://esp-agents-firmware-prebuilt.s3.ap-northeast-1.amazonaws.com/friend/m5stack_cores3/ota_data_initial.bin",
  "https://esp-agents-firmware-prebuilt.s3.ap-northeast-1.amazonaws.com/friend/m5stack_cores3/esp_agent_voice_chat.bin",
  "https://esp-agents-firmware-prebuilt.s3.ap-northeast-1.amazonaws.com/friend/m5stack_cores3/srmodels.bin"
]
image.esp32-s3.addresses = [ "0x0", "0x8000", "0x1c000", "0x30000", "0xe2c000" ]
readme.text = "https://raw.githubusercontent.com/espressif/esp-agents-firmware/refs/heads/main/docs/guides/m5stack_cores3.md"

[[portConnectionOptions]]
console_baudrate = 115200
